# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

include ${LAYERDIR}/include/rz-graphics.inc

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rz-graphics"
BBFILE_PATTERN_meta-rz-graphics := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rz-graphics = "15"

LAYERDEPENDS_meta-rz-graphics = "meta-rz-bsp"
LAYERSERIES_COMPAT_meta-rz-graphics = "scarthgap"

# Poky adds vulkan in DISTRO_FEATURES as default
# But, we do not support it
DISTRO_FEATURES:remove = "vulkan"
